name: rreadtest
favicon: null
layout_spectrum: 0.3224040539935231
typography_spectrum: 0.2483759073074907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.22690798342227936
  lightness: 0.24965736363083124
  saturation: 0.6912184769753367
  rhythmicContrast: 0.8022172567434609
purpose: []
